### ISSUE TITLE
Analytics on SDKs/Integration usage

### ISSUE THREAD

**Issue by gmourier** [meilisearch/product#168]
# Description

Analyze and monitor the distribution of the use of our SDKs/Integrations and thus evaluate the achievement of objectives, efforts to be made, things to improve to offer the best search engine for our users.

**Comment by gmourier** [comment]
# First iteration

In order to calibrate the right format that the search engine will build from the header sent by the SDKs/Integration so that we can establish clear and accurate dashboards, we will perform a first scan to the Rails integration internally. 

## A dedicated header

We will introduce a new header `X-MEILI-AGENT` which will contain the information necessary to understand the use of SDKs and Integrations.

### Example for Rails integration

`X-MEILI-CLIENT`: `MeilISearch Rails (1.0); MeiliSearch Ruby (2.1); Rails (4.0); Ruby (3.0)`

### Example for Ruby SDK

`X-MEILI-CLIENT`: `MeiliSearch Ruby (2.1); Ruby (3.0)`

## Explanations

As integrations use an SDK to communicate with a MeiliSearch instance. We want the SDK to be able to send the information of the integration but also the version of the framework used if there is one and the version of the language.

The integration must be able to send its part so that the SDK can consolidate and transfer the final information to the engine within the `X-MEILI-CLIENT` header.

The search engine will split the different information to consolidate with the `;` character. Finally, the versions will be extracted between the two parentheses `(` and `)`.

We imagine for the moment to consolidate this type of format at the level of the search engine to be able to establish analysis charts on the use of SDKs and integrations.

```json
"clients": [
    {
        "MeiliSearch Rails": {
              "version": "1.0",
        },
       "MeiliSearch Ruby": {
              "version":  "2.1"
        },
       "Rails": {
           "version": "4.0"
       },
      "Ruby": {
           "version": "3.0"
       } 
    } 
]
```

**Comment by curquiza** [comment]
Also, I would like to know which SDK is used "alone" and which one is not.
I mean, can we make the distinction when sending data to Amplitude between:
- `X-Meili-Client: MeiliSearch VuePress (0.12.3); MeiliSearch docs-searchbar.js (1.12.0); MeiliSearch JS (0.16.0)`
- and `X-Meili-Client: MeiliSearch JS (0.16.0)`

?

**Comment by gmourier** [comment]
SDKs also send through `X-MEILI-CLIENT`. However, if we want an overview for those that are used uniquely (so outside of the integration clients), we need to find a format that allows us to do that. Maybe amplitude allows us to distinguish somehow but I have a doubt about that.

**Comment by MarinPostma** [comment]
Why not send a custom user agent, instead of adding a custom header parameter?

**Comment by gmourier** [comment]
Hello @marin. We asked ourselves the question very quickly with @curqui by looking at what algolia does (sometimes it's a user-agent, sometimes a query-parameter, sometimes a custom-header). I noted to make a custom header but by looking at the RFC after your comment https://datatracker.ietf.org/doc/html/rfc2616#page-145 it seems very possible to use User-agent.

The first constraint I imagined (which may not be a constraint) is if the client communicates with a Gateway API before reaching MeiliSearch and needs to override the user-agent at some point.

It would give something like at first sight. We can also use the space as a separator instead of `;`

`User-agent: MeiliSearch-VuePress/0.12.3 MeiliSearch-docs-searchbar.js/1.12.0 MeiliSearch-JS/0.16.0`.

However, this is not the most critical question to solve. The question is mostly about how to build the analytics data and how to send it to Amplitude. (Sending an event batch seems to be mandatory to avoid losing information.)

**Comment by qdequele** [comment]
Hey, it's better to use a user agent. As custom headers could be removed by proxies, or requests with custom headers could be just trashed due to their custom header. I think it's better to avoid that by adding it, as required by the RFC in the `User-Agent` header. Today we are using a custom header for the `X-Meili-API-Key` instead of the `Authorization` official header, and we already had some issues with that.

**Comment by bidoubiwa** [comment]
We wont be able to edit the `user-agent` in chrome browsers, see explanation here:
https://github.com/meilisearch/integration-guides/issues/150#issuecomment-966360488

**Comment by bidoubiwa** [comment]
I was wondering also why we dont follow [the conventional syntax of user-agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) ?
```
User-Agent: <product> / <product-version> <comment>
```

Example: 
```
Mozilla/5.0 (<system-information>) <platform> (<platform-details>) <extensions>
```
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
```

Very sorry if that has been discussed or if we prefer it this way :s I did not find the conversation about it.

**Comment by gmourier** [comment]
Closed since client analytics are implemented on the go.

Support for a `x-meilisearch-client` query parameter is [specified ](https://github.com/meilisearch/specifications/pull/145)and planned for **v0.28**.
