### ISSUE TITLE
Basic MeiliSearch settings configuration

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#230]
# **Problem statement**

As a user, I need to configure my index to match my project needs. 

# Solution

Provide an interface per index that allows the following settings to be configured. 

- Displayed attributes

- Distinct attributes

- Filterable attributes

- Ranking rules

- Searchable attributes

- Sortable attributes

- Stop words

- Synonyms

**Comment by qdequele** [comment]
Link to feature: https://meilisearch.productboard.com/feature-board/planning/features/5032250

**Comment by davelarkan** [comment]
Closing to capture requirement elsewhere
