### ISSUE TITLE
Backup management

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#236]
# **Problem statement**

The ability to shape your projects as needed and whenever you want to adapt your business and stay relevant.

# **Solution**

Allow users to import and export their data with backups.

<p></p>

will work with dumps.

**Comment by qdequele** [comment]
Link to feature: https://meilisearch.productboard.com/feature-board/planning/features/9566822

**Comment by davelarkan** [comment]
Closing to capture requirement elsewhere
