### ISSUE TITLE
Auto Update MeiliSearch minor updates

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#237]
# **Problem statement**

As a user, I need to have the last version of MeiliSearch to be sure that my binary will have the latest features and fit the documentation

# **Solution**

Automatically update instances without any manipulation.

A small downtime could be ok if we update the instances every quarter.

**Comment by qdequele** [comment]
Link to feature: https://meilisearch.productboard.com/feature-board/planning/features/9566886

**Comment by davelarkan** [comment]
Closing issue but will capture this requirement elsewhere
