### ISSUE TITLE
Register/Login with Google

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#359]
# **Problem statement**

As an employee of a company using Google Workspace, I would like to be able to login into the MeiliSearch cloud with a "Login with Google" button.

# Solution

Add a connect with Google button. 

<p></p>

## **Technical Solution**

Could be added directly with Rails Devise or with Auth0/Okta Universal Login.

**Comment by qdequele** [comment]
Link to feature: https://meilisearch.productboard.com/feature-board/planning/features/11057684

**Comment by davelarkan** [comment]
Closing to capture requirement elsewhere
