### ISSUE TITLE
Register/Login with Github

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#360]
# **Problem statement**

As a developer, I would like to be able to login into the MeiliSearch cloud with a "Login with Github" button.

# Solution

Add a connect with Github button. 

<p></p>

## Technical Solution

Could be added directly with Rails Devise or with Auth0/Okta Universal Login.

**Comment by qdequele** [comment]
Link to feature: https://meilisearch.productboard.com/feature-board/planning/features/11057685

**Comment by davelarkan** [comment]
Closing to capture requirement elsewhere
