### ISSUE TITLE
Dump management

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#361]
# **Problem statement**

- As a user, I would need to upgrade/downgrade/duplicate my project

- As a user of the open-source solution, I would like to switch from my open-source solution to the cloud.

# Solution

Allow people to retrieve a dumps then create a project from a dump.

**Comment by qdequele** [comment]
Link to feature: https://meilisearch.productboard.com/feature-board/planning/features/11379672

**Comment by davelarkan** [comment]
Much of the groundwork for this is being completed currently in https://github.com/meilisearch/meilisearch-cloud/issues/1298 and https://github.com/meilisearch/meilisearch-cloud/issues/1299 

I will close this issue and capture any further requirements separately
