### ISSUE TITLE
Deploy a project on GCP

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#362]
# **Problem statement**

As a user of MeiliSearch and GCP, I need to have my servers close by to limit latency. 

# Solution

Allow users to choose between several server providers when creating a project. Add GCP to the list of available servers.

**Comment by qdequele** [comment]
Link to feature: https://meilisearch.productboard.com/feature-board/planning/features/11071629

**Comment by davelarkan** [comment]
Closing this and will capture this requirement elsewhere
