### ISSUE TITLE
Manually upgrade the cloud plan

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#364]
# Context 

Any user who has a service that grows over time or who has underestimated his resource needs to be able to increase the size of his machine easily. 

As described in [the issue dedicated to the pricing](https://github.com/meilisearch/product/issues/235).  We have several plans with dedicated resources per plan. We would like to allow users to upgrade their plans when they want and Instantly.

Today, it's technically impossible to downgrade a plan because it's impossible to downgrade the disk size. It's not really a problem because the user needs today that we are trying to solve is to help them upgrade resources if their application grows with time. 

# Objectif

Allow users to upgrade their plan to take a server with more RAM/CPU/Disk. 

# Todo
### Design
- [x] https://github.com/meilisearch/design-team/issues/27

### Dev
- [x] https://github.com/meilisearch/meilisearch-cloud/issues/411

**Comment by qdequele** [comment]
Link to feature: https://meilisearch.productboard.com/feature-board/planning/features/11071615

**Comment by chayaline** [comment]
Here is our issue on design side https://github.com/meilisearch/design-team/issues/27
