### ISSUE TITLE
Configure API Keys

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#366]
# **Problem statement**

As a user, I need to be able to retrieve and manage my API keys to facilitate my use. 

# Solution

Provide an interface per index that allows the user to see and manage its API Keys. 

<p></p>

## Technical Solution

Hypothesis: Don't allow to modify the Default Search/Admin API Key. See with Guillaume

**Comment by qdequele** [comment]
Link to feature: https://meilisearch.productboard.com/feature-board/planning/features/5032252

**Comment by davelarkan** [comment]
Closing - Users can access the Master Key as well as the Default search and Admin keys via the UI.
I will capture an improvement in this area (to allow users to change/rotate keys through the UI) elsewhere
