### ISSUE TITLE
Consider returning `taskUid` instead of `uid` on the `202 Accepted` Summarized Task response

### ISSUE THREAD

**Issue by gmourier** [meilisearch/product#368]
In `202 Accepted` responses, the associated task identifier is returned via the `uid` field, but in this case we are not in the context of direct use of task routes, which could mislead a user.

One solution could be to name the field `taskUid` instead of `uid` in this case.

**Comment by bidoubiwa** [comment]
I agree :) 
While having 
```js
{
  taskUid: 1
  indexUid: "movies",
  batchUid: 3,
}
```

Could be very clear to the user that all information related to his actions are available here and every information is very clear in what is suggests.

**Comment by gmourier** [comment]
Small technical point, we will not be able to have the `batchUid` in the `202`, because they are defined later in the work flow 🤓

**Comment by curquiza** [comment]
Checked with @gmourier, we adopt this in v0.28.0 🚀

**Comment by gmourier** [comment]
Closed since [specified](https://github.com/meilisearch/specifications/pull/144) and planned for **v0.28** release.
