### ISSUE TITLE
Get many / batch documents by ids in one request to meilisearch

### ISSUE THREAD

**Issue by vitalijm** [meilisearch/product#372]
Lang: PHP
Hi, how we can natively do one request to meilisearch to get multiple documents?

I know how we can retrieve natively one document with func **getDocument**:
`$client->index('movies')->getDocument(42);`

[getDocuments: documentation](https://docs.meilisearch.com/reference/api/documents.html#get-documents)
But with func **getDocuments** I don't know how to retrieve multiple documents natively by one request:
`$hits[] = $client->index('movies')->getDocuments([42,43]);`

Or this is not neccessary, because in all situations all documents will be retrieved by meilisearch internal logic using **getDocument** function?

**Comment by gmourier** [comment]
Hello @vitalijm!

This is not possible for now to retrieve a set of specific documents from their id from the `/documents` endpoint, you are right. We will work on this endpoint this year to stabilize it before a v1.0 and consider adding that kind of capability.

**Comment by vitalijm** [comment]
Great!
