### ISSUE TITLE
Manage project status

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#404]
# Context
In order to allow users to better understand the state in which their service is, we decided to work on the possible status of a server and the way we want to display them. 

# Objective
Have a clear view of the status of the server. Know quickly if the server is ready to be used or not. 

# Explanation
The status could have the following states:
- Creating: When the project is creating, for the first time. With animated dots.
- Updating: When any update is going on. With animated dots.
- Failed: When the project crashed. When we’ll be able to do so, a message explaining the reasons will be displayed next to it.
- Running: When the project is accessible and running smoothly.
- Stopped: When the project is stopped for any reason that’s not an error.

# Todo
### Design
- [x] https://github.com/meilisearch/design-team/issues/25

### Dev
- [x] https://github.com/meilisearch/meilisearch-cloud/issues/923

**Comment by chayaline** [comment]
@qdequele I believe this issue is done on the design side. I completed everything needed on the issue description. 
For now, we can't display the reasons if the server fails, but when we'll be able, we'll simply have a message next to the status tag.

**Comment by qdequele** [comment]
@chayaline I prefer to have an issue also here to be able to track the progress of the task on the dev side as well.

**Comment by chayaline** [comment]
What do you think of the idea of having a small status indicator inside the project's header?
This way the status would be visible from all the subpages, not just from the overview. 

![Capture d’écran 2022-03-03 à 15 55 19](https://user-images.githubusercontent.com/16258667/156590179-080415d8-8293-4d96-96c2-4d93a6dbc405.png)

Vercel does it, for example. And they take it a step further with the favicon 😅 
<img width="46" alt="Capture d’écran 2022-03-03 à 15 57 33" src="https://user-images.githubusercontent.com/16258667/156590446-16104635-e5ca-42d4-835a-5555db950eb3.png">
<img width="557" alt="Capture d’écran 2022-03-03 à 15 57 26" src="https://user-images.githubusercontent.com/16258667/156590448-e50fd45e-1b2b-4873-89a4-468c8b0bdc0d.png">

Using color only is not the best thing accessibility wise though, but it can be tweaked. And as it's not the only place where they can see the status, could be ok 🤔

**Comment by qdequele** [comment]
I like the idea to have the status on every sub pages. On Vercel they have added this.. It seems not enough. 
![Screenshot 2022-03-03 at 18 21 03](https://user-images.githubusercontent.com/6064892/156617554-21f6699f-0444-4ed7-a20c-1474d033b3dd.jpg)

**Comment by davelarkan** [comment]
Closing this tracking issue and will capture this elsewhere
