### ISSUE TITLE
Notify/alert the user when needed

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#405]
# Context

# Objective

# Todo
### Design
- [ ] https://github.com/meilisearch/design-team/issues/20

**Comment by chayaline** [comment]
Here are the designs:
- [notification component](https://www.figma.com/file/ra4Vg1838vs07h8Wyttmn8/?node-id=9%3A6) - _done_
- [notification panel](https://www.figma.com/file/ra4Vg1838vs07h8Wyttmn8/?node-id=101%3A23) - _in final review_

**Comment by davelarkan** [comment]
Closing this tracking issue. Will capture the requirement elsewhere.
