### ISSUE TITLE
Generate user and project slug

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#406]
# Context
In order to be able to identify a user and a project in a unique way, especially for the URLs of the dashboard and the URLs of the projects, we have identified the need to generate slugs for the users and for the projects. 

[Definition of a Slug](https://en.wikipedia.org/wiki/Clean_URL#Slug):
1. Some systems define a slug as the part of a URL that identifies a page in [human-readable](https://en.wikipedia.org/wiki/Human-readable_medium) keywords.[[4]](https://en.wikipedia.org/wiki/Clean_URL#cite_note-4)[[5]](https://en.wikipedia.org/wiki/Clean_URL#cite_note-5) It is usually the end part of the URL (specifically of the [path](https://en.wikipedia.org/wiki/Uniform_Resource_Locator#path) / [pathinfo](https://en.wikipedia.org/wiki/Uniform_Resource_Locator#pathinfo) part), which can be interpreted as the name of the resource, similar to the [basename](https://en.wikipedia.org/wiki/Basename) in a [filename](https://en.wikipedia.org/wiki/Filename) or the title of a page. The name is based on the use of the word [slug](https://en.wikipedia.org/wiki/Slug_(publishing)) in the news media to indicate a short name given to an article for internal use.
2. Slugs may be entirely lowercase, with accented characters replaced by letters from the [Latin script](https://en.wikipedia.org/wiki/Latin_script) and [whitespace characters](https://en.wikipedia.org/wiki/Whitespace_character) replaced by a [hyphen](https://en.wikipedia.org/wiki/Hyphen) or an [underscore](https://en.wikipedia.org/wiki/Underscore) to avoid being [encoded](https://en.wikipedia.org/wiki/Percent-encoding). Punctuation marks are generally removed, and some also remove short, common words such as [conjunctions](https://en.wikipedia.org/wiki/Conjunction_(grammar)). For example, the title This, That, and the Other! An Outré Collection could have a generated slug of this-that-other-outre-collection.

Before the arrival of the slug, when a user created an account we asked for the full name. We will have to change this way of creating an account to allow users to choose a user slug. 
<img src="https://user-images.githubusercontent.com/6064892/157200302-3a2051b0-69b2-4ff0-82a7-d2224ad19ca5.png" alt="alt text" width="400">

Before the arrival of the slug, when a user created a new project, we asked for a project name. We will have to change this way of creating a project to allow users to choose a user slug. 
<img src="https://user-images.githubusercontent.com/6064892/157200604-e5d9ae64-f928-4163-862f-dba5783a840d.jpg" alt="alt text" width="400">

# Objectives 

-  What is the writing convention for a slug?

## Project
- how to introduce the choice of the project slug?
- What is the URL to access a project on the dashboard
- What is the API route to update a project slug

## User
- how to introduce the choice of the user slug?

# Ressource

## What is doing Github
<img src="https://user-images.githubusercontent.com/6064892/157202870-e1d9df50-48b4-4027-9800-e486baf6d19c.jpg" alt="alt text" width="400">
<img src="https://user-images.githubusercontent.com/6064892/157202890-bf4a3561-64df-41ad-89f4-8922270fa81a.jpg" alt="alt text" width="400">
<img src="https://user-images.githubusercontent.com/6064892/157202912-a3450ff2-4935-44b5-b77a-497dfc52f445.jpg" alt="alt text" width="400">

## What is doing Netlify
<img src="https://user-images.githubusercontent.com/6064892/157212553-edd5878a-287f-4d16-bbe6-4d47508848ba.jpg" alt="alt text" width="400">
<img src="https://user-images.githubusercontent.com/6064892/157212765-83e6564a-bebe-41ef-8ba3-e3ce9918ffd0.jpg" alt="alt text" width="400">
<img src="https://user-images.githubusercontent.com/6064892/157212768-9970ebb9-74f2-4a74-9894-1c994893fb42.jpg" alt="alt text" width="400">

# Decisions

## What is a slug
A slug is a string of characters with no spaces that can only contain a-z, 0-9, and hyphens. It cannot start or end with a hyphen.  

## Users slugs (Username)
Today, when registering, people are asked to fill in their "name" which is a free field. I propose that we change the "name" field to "username" which should be formatted as a slug. 
For people who already have an account, we should be able to generate their username from their name. If there is a name conflict, it is possible to add a number to the end. 
The username can be used to uniquely identify a person and can also be used in URLs instead of the user id (UUID).

Questions that could remain to be answered. 
- How are project URLs affected by changing usernames? I suggest that changing the username is not proposed at this time. 

## Projects slugs (project id)
For projects, the slug will not really be front-end. It will mainly be used in dashboard URLs and project URLs. We, therefore, propose to keep the project name as it is today but to generate it in the backend project id which is the project slug. This information will never be shown on any interface.

Questions that could remain to be answered. 
- How are project URLs affected by changing projects names? 
    - We can change the project name but the slug will still be the same.
    - We can don't allow to change the project name. They have to delete and recreate a project.
    - The project URLs don't change even if the project name change. 

# Todo
- [x] https://github.com/meilisearch/design-team/issues/28

**Comment by davelarkan** [comment]
Closing – will add this to backlog for further improvement.
