### ISSUE TITLE
Add sort feature

### ISSUE THREAD

**Issue by gmourier** [meilisearch/product#43]
# Description

Allow sorting from a `sortBy` parameter at search time. 
It should be possible to sort numeric and alphanumeric values in `asc/desc` order.

# Pain points

Users today must find workarounds that take time to develop and maintain. It's not simple enough.

One workaround is to make multiple indexes with precise custom ranking rules for each possible sort rule and choose the right index from user input and send the search request to a specific index.

# Why is it under consideration?

It is critical for a search engine to be able to offer this feature, especially for e-commerce use. Moreover, competitors all offer it.

According to our user feedback sortBy feature is mentioned as one of the biggest deal-breakers when it comes to choosing MeiliSearch as a search engine.

**Comment by gmourier** [comment]
# Working group note - 2021-07-06

## Attendees
@bidoubiwa, @qdequele, @ManyTheFish, @irevoire, @guimachiavelli

## Goals
- Answer technical questions
- Identify the do and don’t
- Start to converge on a possible solution

## Summary Key Points

- Sortable attributes should be known by the engine before search time. 
- If we don't support sortBy on string parameter, the feature could be made quicker. A specific data structure must be added to sort alphanumeric fields.
- Sort can operate on multiple fields at search time.
- For now, we **WON'T** supports sort on nested fields.
- We **WON'T** support computational functions `avg, sum, min, max, median`. e.g. `sortBy="avg(price:desc)"`.  A workaround is to pre-compute values in the document before indexing and sorts them at search time. e.g. `sortBy="avg_price:desc"`.
- sortBy attributes are added at search time on top of the ranking rules set.
- The feature **WON'T** deal with the ability to set a custom ranking rules order at search time.

## Next Step

Present a solution prototype with examples and API definitions proposal in a working group.

**Comment by dichotommy** [comment]
Hey, thanks for posting your notes! Following this.

**Comment by gmourier** [comment]
# sortBy feature - Proto-solution

## Context

This document will address the first part of the next steps, i.e., to propose an API design allowing to fulfill the objectives previously fixed concerning the sortBy.

---

### As a developer, I want to configure the sortable attributes so that the end-user can sort results.

- Introduce a new field in the global settings resource. 
- Introduce a new sub-setting resource sortable attributes.

#### Field definition

[string] `sortableAttributes` nullable

#### GET settings

##### 200 - Response without empty sortableAttributes (Default)

```json=
{
    ...,
    "sortableAttributes": []
    ...
}
```

##### 200 - Response with already configured sortableAttributes
```json=
{
    ...,
    "sortableAttributes": ["price", "released_date"]
    ...
}
```
> 💡 The values order in sortableAttributes has no impact. The order will be determined at search time.

#### POST settings

##### Request body
```json=
{
    ...,
	"sortableAttributes": ["price", "released_date", "title"],
    ...
}
```

##### 202 Accepted - Response body

```json=
{
    "updateId": 7
}
```

> 💡 Posting other than string value results in an `invalid_request_error`.
> 💡 Posting an inexistent field will not throw an error.
> 💡 `sortableAttributes` accepts `null` and `[]` values.

#### DELETE settings

> 💡 Resetting all settings will result in default case e.g. `sortableAttributes: []`
> 
##### 202 Accepted - Response body
```json=
{
    "updateId": 8
}    
```

#### GET settings/sortable-attributes

##### 200 - Response body (Default)
```json=
[]
```

##### 200 - Response body with already configured sortableAttributes
```json=
[
    "price",
    "released_date"
]
```

#### POST settings/sortable-attributes

##### Request body

```json=
["price", "released_date", "title"]
```
##### 202 Accepted - Response body

```json=
{
    "updateId": 7
}
```

> 💡 Posting other than string value results in an `invalid_request_error`.
> 💡 Posting an inexistent field will not throw an error.
> 💡 Request body accept `null` and `[]` values.

#### DEL settings/sortable-attributes

##### 202 Accepted - Response body
```json=
{
    "updateId": 8
}    
```

---

### As an End-User, I want to sort alphanumeric and numeric attributes in ascending/descending order so that I can find easily what I want when I'm searching.

- Introduce a `sortBy` query parameter on the search endpoints

#### sortBy parameter definition

> ❓ Since a document attribute can contains `:`, `(`, `)` we need to find a way to detect that a specific field wants to be sortBy `asc` or `desc`.
> 
> One way can be to detect `:asc` or `:desc` ending pattern.

e.g. GET 

`...&sortBy="price:asc,released_date:desc"`

e.g. POST
```
{
    "q": "",
    "sortBy": [
        "price:asc",
        "released_date:desc"
    ]
}
```

We need to find a consistent way of writing parameters between GET and POST routes.

One way can be writing GET parameters this way.

`...&sortBy[]="price:asc"&sortBy[]="released_date:desc"`

We need to align the custom ranking rules way of writing with the sortBy parameters.

```json=
//Ranking Rules
[
    "asc(title)"
    //can become
    "title:asc"
]
```


#### Search with sortBy example

e.g. with this document set

```json=
[
    {
        "id": 1,
        "label": "Vans Classic II sweatshirt in black",
        "price": 52.00,
        "colors": ["black"],
        "sizes": ["xs", "s", "m", "m", "xl"],
        "reviews_rating": 4.5
    },
    {
        "id": 2,
        "label": "The North Face Drew Peak hoodie in green",
        "price": 36.00,
        "colors": ["green"],
        "reviews_rating": 4.89
    },
    {
        "id": 3,
        "label": "Nike Club hoodie in navy",
        "price": 52.00,
        "colors": ["navy"],
        "reviews_rating": 4.7
    }
]
```

e.g. with this sortBy query parameter 

```json=
{
    ...,
    "sortBy" = [
        "price:asc",
        "reviews_rating:desc"
    ]
}
```

> 💡 Consider that sortBy values are set as sortable-attributes

##### What happens on the ranking rules side?

The `sortBy` attributes set at search time are put on top of the existent ranking rules ordered as they are written, let's illustrate it.

e.g. given that ranking rules setting

```json=
[
  "typo",
  "words",
  "proximity",
  "attribute",
  "wordsPosition",
  "exactness",
]
```

If we use that `sortBy` query parameter definition

```json=
{
    "q": "",
    "sortBy": [
        "price:asc",
        "reviews_rating:desc"
    ]
}
```

Ranking rules can virtually be represented that way for this search request.

```json=
[
  "asc(price)", //asc(price) is virtually added on-top for this search
  "desc(reviews_rating)", //desc(reviews_rating) is virtually added on-top for this search
  "typo",
  "words",
  "proximity",
  "attribute",
  "wordsPosition",
  "exactness",
]
```

##### Expected search result

```json=
[
    {
        "id": 2,
        "label": "The North Face Drew Peak hoodie in green",
        "price": 36.00, //first SortBy rule is to order document in ascending order by price
        "colors": ["green"],
        "reviews_rating": 4.2
    },
    {
        "id": 3,
        "label": "Nike Club hoodie in navy",
        "price": 52.00, //Since document 3 and document have the exact same price, they are ordered by descending reviews_rating
        "colors": ["navy"],
        "reviews_rating": 4.7
    },
    {
        "id": 1,
        "label": "Vans Classic II sweatshirt in black",
        "price": 52.00,
        "colors": ["black"],
        "sizes": ["xs", "s", "m", "m", "xl"],
        "reviews_rating": 4.5
    }
]
```

---

This proto-solution seems to be suitable for what we want to do from the last working-group identified needs. 

Some questions still need to be answered: 

- Which format do we choose to define a sortBy attribute at search time. `attribute_name:asc`, `asc(attribute_name)`, `attribute_name asc`?
- Should we update the custom ranking rule format if we choose a format different than `asc(attribute_name)`?
- Are the naming proposal correct? `sortable-attributes` and `sortBy`?

We will conduct a working group to validate this proto-solution and these questions to move towards a specification.

**Comment by gmourier** [comment]
# Working group note - 2021-07-13

## Attendees

@Kerollmops, @ManyTheFish, @gmourier

## Goals

We realized that the proposed pre-solution of placing the criteria associated with the sortable attribute before the ranking rules in the search  (**Solution 1** in the following white-board image) would not meet the relevancy search needs of most of our users. To do so would be to have an exhaustive sorting rather than relevancy in part because of the way tie-breaking algorithms work.

## Summary Key Points

We have explored several solutions with their advantages and disadvantages. We found a solution that would allow the user to choose whether he wants an exhaustive or relevant sort within the settings without additional complications for the user and the technical team.

![IMG_0969](https://user-images.githubusercontent.com/3692335/125444960-82cecb31-0c20-4d3e-ab0a-e23732511129.jpg)

### Chosen Solution (Number 5 on the white-board)

![Capture d’écran 2021-07-13 à 13 46 23](https://user-images.githubusercontent.com/3692335/125447461-f89657c3-92ff-4844-926d-93b2e22c51f0.png)

This is a solution that we would like to test because it allows the user to adjust the level of relevancy/exhaustiveness in the use of the sort by allowing him to place it where it seems best according to his use case.

It is also a solution that is technically easier to implement than solution 4 where we wanted to include a percentage calculation to rule on the behavior of the buckets' slices. This calculation is difficult to explain and it is necessary to add a setting allowing the user to choose the percentage he wants. Complexities are therefore introduced in the use, the technique, and the explanation.

## Explanation and changes to the pre-solution

- The search endpoint is not affected.
- The sortable-attributes endpoint is not affected.

The only important change is that we introduce a new ranking rule that can be set according to the preference of the search engine maintainer to choose how much the sorting will matter.

Like the previous solution, where the sorting attributes were placed at the top of the ranking rules list from the moment the sorting was requested during the search. The DynamicSort ranking rule will be active only when the `sort`/`sortBy` parameter is present at search time.

### e.g. Exhaustive Sort

I want an exhaustive sort. I put the DynamicSort at the highest level of my ranking rules so that it becomes a strong discriminant.

```
[
  "dynamicSort",
  "typo",
  "words",
  "proximity",
  "attribute",
  "wordsPosition",
  "exactness",
]
```

At search time, if I use (knowing that `price` and `reviews_rating` are set as `sortable-attributes`)

{
    "q": "",
    "sortBy": [
        "price:asc",
        "reviews_rating:desc"
    ]
}

Ranking rules can virtually be represented that way for this search request.

[
  "asc(price)", //asc(price) is virtually added on-top for this search (dynamicSort)
  "desc(reviews_rating)", //desc(reviews_rating) is virtually added on-top for this search (dynamicSort)
  "typo",
  "words",
  "proximity",
  "attribute",
  "wordsPosition",
  "exactness",
]

### e.g. Relevant Sort

I want a relevant sort (sort on relevant items). I put the DynamicSort at the latest level of my ranking rules so that it becomes a soft discrimant.

```
[
  "typo",
  "words",
  "proximity",
  "attribute",
  "wordsPosition",
  "exactness",
  "dynamicSort"
]
```

At search time, if I use (knowing that `price` and `reviews_rating` are set as `sortable-attributes`)

{
    "q": "",
    "sortBy": [
        "price:asc",
        "reviews_rating:desc"
    ]
}

Ranking rules can virtually be represented that way for this search request.

[
  "typo",
  "words",
  "proximity",
  "attribute",
  "wordsPosition",
  "exactness",
  "asc(price)", //asc(price) is virtually added on-top for this search (dynamicSort)
  "desc(reviews_rating)", //desc(reviews_rating) is virtually added on-top for this search (dynamicSort)
]

**Comment by Kerollmops** [comment]
I like the last solution you describe, however it would be preferable to use the already known syntax `Asc(price)`, `Desc(reviews_rating)` for the `sortBy` parameter instead of introducing a new one i.e. `price:asc`, `reviews_rating:desc`.

I am also not a big fan of using the `sortBy` parameter name, that is a different name than `dynamicSort`, maybe we should use `dynamicSortBy` in the search query and keep `dynamicSort` in the ranking rules, maybe use `dynamicSort` on both side?

**Comment by gmourier** [comment]
Hello @Kerollmops, glad to see your comment here! 🖖 

I didn't have time to update the discussion here. We had taken some decisions about naming.

## Naming suggestions

- Setting parameter name and resource name: `sortable-attributes`
- Search parameter: `sort`
- Search parameter syntax: `price:asc`
- New Ranking Rule name: `sort`

We also want to update the custom ranking rule syntax to `price:asc` to keep a convention.

I feel like we're pretty much aligned. What do you think?

**Comment by gmourier** [comment]
Specification https://github.com/meilisearch/specifications/pull/55

**Comment by gmourier** [comment]
Here are the metrics we would like to measure per MeiliSearch instance to better understand how our users use it.

- Number of sorted attributes used in `sort` search parameter to calculate an avg per server.
- Position of the `sort` ranking rule in the `ranking-rules`.
- Number of `sortableAttributes` to calcule an avg per server.

**Comment by gmourier** [comment]
# `sort` VS `custom ranking rule`

## History of the custom ranking rule

Custom ranking rules exist to promote documents without user action according to a specific need.

Initially, developers who wanted to be able to give the possibility to sort at search-time to the end-users were compelled to create an equivalent index with a custom ranking rule for each field and order.

Let's say we have a list of products and we want to give the user the possibility to sort by descending and ascending price.

Two indexes with the exact same documents were mandatory. Here are the ranking rules they had to implement.

Index uid `products_price_desc` - Ranking rules definition

```json
[
    "words",
    "typo",
    "proximity",
    "attribute",
    "exactness",
    "desc(price)"
]
```

Index uid `products_price_asc` - Ranking rules definition

```json
[
    "words",
    "typo",
    "proximity",
    "attribute",
    "exactness",
    "asc(price)"
]
```

On the client-side, a selector of sort rules allows changing indexes in a transparent way.

✨ This is a hack that won't be necessary anymore and will give back to the custom ranking rule its original purpose. No more need to create multiple indexes and manage them. 😎

## What does it becomes with the `sort` ranking rule?

💡 The custom ranking rule should be seen as what it was meant to be in the beginning. A default criterion to be forced for every search query.

Let's imagine a use case where this could be useful in addition to the use of `sort` at search time.

Let's say you're a bookseller and you'd like to see books with a current discount be put first in the search results because you believe that it promotes the buying action of the end-users.


```json
[
    {
        "id": 1,
        "title": "Hey, read me",
        "has_discount": 1,
        "price": 4.99,
        "discount_price": 2.99
    },
    ...
    {
        "id": 389575,
        "title": "Hey, read me please",
        "has_discount": 0,
        "price": 9.99,
        "discount_price": null
    }
]
```

As the distribution is very good on the field `has_discount` because it contains only two possible values, it will allow to make two distinct groups of documents during the tie-breaking algorithms pass.

Example of the custom ranking rules that will put discounted document first.

```json
[
    "discount_price:desc", //since it's an integer, desc put `1` value before `0`
    "words",
    "typo",
    "sort"
    "proximity",
    "attribute",
    "exactness"
]
```

From now, books with a discount price will be selected as better candidates than books without a discount price. 

A filter would have been too discriminating here because it would have excluded all books without a promotion, which is not necessarily what is intended.

✨ We can see here that the custom ranking rule is used as a simple business rule but quite powerful.

🙋🏻‍♂️ "Hey that's great. What if I want to give my users the ability to sort by price through the books that have a promotion?"

Just define the `price` field as a sortable attribute, the order will be decided by the user depending on what he wants.

`POST` - `indexes/books/settings/sortable-attributes`
```json
[
    "price"
]
```

From now, the end-user will be able to sort by price in ascending or descending order within the books that are considered more relevant (in our case those with a discount). Use the `sort` search parameter `price:desc` / `price:asc`.

🙋🏻‍♂️ "Hey I already have a custom ranking to sort the documents by price. Should I keep that rule?"

Not really. Unless you don't want to give the user a choice to sort on that field.

If you want to give the user a choice and provide a default sort, it's easier to remove this custom ranking rule and use `sort` with a default value on the client-side. For example `"sort=price:desc"`

If ever you had defined your custom ranking rule position before the `sort` ranking rule.

```
[
    "price:desc",
    "words",
    "typo",
    "sort",
    ...
]
```

💡 Sending `sort=price:asc` at search time will have no impact on the returned order. In this case, you have to place the custom ranking rule after the `sort` one so that users can change the order at search time. If `sort` is not sent at search time it will fall back to the custom ranking rule ordering. This is because of the tie-breaking algorithm inner-working.

```
[
    "words",
    "typo",
    "sort",
    ...,
    "price:desc"
]
```

💡 Sending `sort=price:asc` is now working while the default sort order stay as `price:desc` when `sort` is not sent at search time.

📚 The order of the ranking rules is important, if you want to keep a custom ranking rule to define the default ordering of a field that is sortable by end-users, put it after the `sort` ranking rule but since the order can be changed by the user, you should prefer sending `sort` with a default value equivalent to the custom ranking rule and remove that custom ranking rule for clarity. The real strength of the custom ranking rule lies in the fact that it allows selecting some documents before others on a custom rule. Fields with very few possible values within the documents are to be favored in order to make the custom ranking rule efficient. See the `has_discount` example.

 🙋🏽‍♀️ "Why did you put `sort` after `words` and `typo` by default?"

We believe this is the most natural position to provide a good search experience. The balance is set between exhaustivity and relevancy because it let `words` and `typo` tie-breaking phases select some documents according to what these ranking rules promote before sorting them. You can always change the position of the `sort` ranking rule but chances are you won't have to touch it.

## Bonus

- Custom ranking rule can now be set on a string field.

**Comment by francoism90** [comment]
@gmourier Does this work with filtered values?

I'm using something like this:
```php
$client->index('movies')->search('*', ['filter' => 'id = 20, id = 10, id = 30']);
```
When no sort is giving, I expect item 20 first, 10 second and 30 third. However, the results still seems to be based on relevance.

I'm I missing something here? I cannot do `sort => `id:asc` because this would result in: 10, 20, 30 ..

Thanks.

**Comment by gmourier** [comment]
Hello @francoism90

Filters allow you to select documents based on certain criteria, then sorting is applied to them if specified. The filters do not sort the documents.

Here, you don't have any criteria to return your documents in the desired order. Why do you want to return the documents in this order?  Is it to put these particular documents forward in a specific order?

Thank you for your answer!

**Comment by francoism90** [comment]
@gmourier  Yep, I would indeed show documents in a given order.

To give you some context, using Laravel Scout:
```
// Placeholder search
$ids = [20, 10, 30];

return Search::('*')->whereIn('id', $id); // expect to return: 20, 10, 30
```

```
// Relevance search

$ids = [20, 10, 30];

return Search::('foo')->whereIn('id', $id); // results: 10, 30, 20
```

You can apply a sorter like `id:asc`, but maybe something like `id:ordered` would be a nice feature.

Maybe this is already possible and Laravel is just removing the ordering? :)

Thanks!

**Comment by gmourier** [comment]
We should move on to a dedicated product discussion to make the discussion more visible and focused on these needs. In this particular case, it seems to me that MeiliSearch returns the default order of the documents in the database. MeiliSearch is not able to define a specific order. 

The sort can only be ascending or descending and is triggered after or before the tie-breaking of other ranking rules, it depends on the position of the sort ranking rule among them. For a placeholder search (aka without any term) entered by the end-user, MeiliSearch will not be able to define an order other than strict ascending or descending since no other ranking rules will be triggered to mitigate the position by relevancy.
