### ISSUE TITLE
API keys and Multi-Tenant support

### ISSUE THREAD

**Issue by gmourier** [meilisearch/product#51]
# Description

Manage `API keys` from MeiliSearch with restrictions (ACL, expiration date, accessible indexes). 

Use these `API keys` to generate `Scoped API keys` per end-user on the user side server to solve multi-tenancy use-case.

**Comment by binaryfire** [comment]
Really looking forward to this feature! We're building an e-commerce SaaS where each customer has their own shop (and index). And we want to run a single instance of Meilisearch on the server which can handle all the indexes :)

**Comment by gmourier** [comment]
# Working group note - 2021-09-29

## Attendees
@alallema , @MarinPostma , @Kerollmops , @nicolasvienot , @gmourier

## Motivation

In order to make MeiliSearch more reliable, we need to improve the management of data access security. We are going to improve the management and the possibilities of restrictions of the API keys. Security is a critical need, often difficult to negotiate as the stakes are so high for a company. 

It will also solve the multi-tenancy use case. By managing this natively, we reduce one of the last major deal-breakers that makes users not choose MeiliSearch as a solution despite all our advantages.

Multi-Tenant API keys are regularly requested by users over time. Users today need to set up workarounds to meet this need. Some implement reverse-proxy or managed authentication systems like Hasura or Kong to filter what can and cannot be read. Others decide to use server code as a facade to implement the access restriction logic before requesting MeiliSearch.

It is obviously difficult to maintain, less efficient, and requires necessary skills that not everyone has.

## User's needs

- Allow MeiliSearch to be used by a larger technical team. By proposing a system of rights to delimit the fields of action for certain API keys, MeiliSearch is more secure and operable by technical teams. 
- Gain confidence in MeiliSearch's ability to provide a means to ensure secure access to certain data. The most clearly established need, regularly requested by SaaS is to be able to manage Multi-Tenant uses-cases. This means restricting access to data to authorized users only. This need naturally imagined to restrict access to certain documents within an index can also be extended to the level of an index.
- Another objective could be to be able to manage this data governance over time. Implementing a key expiration system would allow guaranteeing access for a certain time only chosen by the user who generates the access keys.

## Working Group Goals

- Answer and ask technical questions
- Identify the do and don’t
- Start to think and draft a possible solution

## Summary Key Points

- API keys generated by MeiliSearch users MUST be stored and be manageable from API endpoints.
- Stored API Keys MUST be able to restrict access to indexes, methods (ACL), and can have an expiration time.
- Virtual Keys MUST be generated on the user's server to secure access to end-user documents within an index with forced filters at search time.
- These virtual keys MUST be derived from a stored API key and can only have fewer restrictions. They are only usable for search in this first iteration and are forced to have an expiration time.
- We WON'T implement a rate-limiting feature for this first iteration.

## Next Step

- @meilisearch/product-team - Present a solution prototype with examples and API definitions proposal in a proto-solution for API Keys management and Multi-Tenancy Virtual API Keys.
- @meilisearch/core-team - Verify and recommend a solution that meets the product needs and technical constraints among JWT, Biscuit, and other solutions to generate virtual search keys on the user's server-side.

**Comment by gmourier** [comment]
# Api Keys Proto-Solution

## Summary Key Points

- `/keys` endpoints becomes restricted to the master key.
- When a `master` key is set at MeiliSearch first-launch, we can generate two pre-configured Stored `API Keys`. A `Default Search API Key` restricted to the `search` action and a `Default Admin API Key` key to handle all operations (except managing API Keys) on MeiliSearch.
- New endpoints are added to manage the `keys` resources.
- `API keys` can have restrictions on which methods can be accessed via an `actions` list, they can also expire after a certain amount of time and be restricted to a specific set of indexes.
- `Virtual Scoped keys` are generated from a MeiliSearch `API key` on the client's server code to resolve multi-tenancy use-case by restricting access to data within an index according to the criteria chosen by the team managing a MeiliSearch instance. These virtual can't be less restrictive than a parent `API key` and can only be used for search. These are not stored and retrievable on MeiliSearch.

---

## Glossary

| Term               | Definition |
|--------------------|------------|
| Master Key         | This is the master key that allows you to create other API keys. This key is defined by the user when launching MeiliSearch. |
| API Key            | API keys are stored and managed from the endpoint `/keys` by the master key holder. These are the keys used by the technical teams to interact with MeiliSearch at the level of the client code. |
| Scoped API Key | These keys are not stored and managed by a MeiliSearch instance. They are generated for each end-user by the backend code of a user from an API key. They are used to restrict the end user to search and access only the documents belonging to him. |
| Multi-Tenancy      | By multi-tenancy, we mean that an end-user only accesses data belonging to him within an index shared with other end-users. |

---

## Diagrams

### API Keys Management

#### Managing `API Key`

![](https://i.imgur.com/mAUFnNb.png)

Anna manages the MeiliSearch instance, she uses the master-key she defined at startup to generate an `API Key` resource for Mark so that he can use it in his client code to communicate with the MeiliSearch instance.

Anna has the possibility to define access rights to certain indexes, to define an expiration date and also authorized `actions` (ACL) for this `API Key`.

Only the master-key allows to manage the API keys.

---

#### Using an `API Key` to communicate with MeiliSearch

![](https://i.imgur.com/kRKcB43.png)

Mark receives the `API Key` transmitted by Anna on a secured channel. He uses it to authenticate the requests to MeiliSearch.

---

## `API Key` Endpoints Proto-Solution

### **As `Anna`, I want to create an API keys for `Mark` client-code, so that he can index  some documents**

---

#### Actions List Definition

> `:authorizedIndexes` can be as the possible value for the `indexes` field of an  `API key` object.

| name    | description |
|---------|-------------|
| search  | Provides access to `GET` and `POST` methods on `/indexes/:authorizedIndexes/search` routes. |
| documents.add | Provides access to `POST` and `PUT` on `/indexes/:authorizedIndexes/documents` routes. |
| documents.get | Provides access to `GET` methods on `/indexes/:authorizedIndexes/documents/` `/indexes/[:authorizedIndexes]/documents/:documentId` |
| documents.delete | Provides access to `DELETE` method on `indexes/:authorizedIndexes/documents/:documentsId`, `indexes/:authorizedIndexes/documents/:documentsId` and `POST` method on `indexes/:authorizedIndexes/documents/delete-batch` routes. |
| indexes.add | Provides access to `POST` `/indexes`. The newly created `index` is added to the `indexes` array for this key and all others keys having `[*]` as a value for `indexes`. |
| indexes.get | Provides access to `GET` `/indexes` and `/indexes/:authorizedIndexes`. Non-authorized `indexes` are ommited from the response on `/indexes`. |
| indexes.update | Provides access to `PUT` `/indexes/:authorizedIndexes` |
| indexes.delete | Provides access to `DELETE` `/indexes/:authorizedIndexes` |
| tasks.get | Provides access to `GET` `/tasks` and `/indexes/:indexUid/tasks` routes. |
| settings.get | Provides access to `GET` `/indexes/:authorizedIndexes/settings` and `/indexes/:authorizedIndexes/settings/*` routes. |
| settings.update | Provides access to `POST` `/indexes/:authorizedIndexes/settings` and `/indexes/:authorizedIndexes/settings/*` routes. |
| settings.reset | Provides access to `DELETE` `/indexes/:authorizedIndexes/settings` and `/indexes/:authorizedIndexes/settings/*` routes. |
| stats | Provides access to `GET` `/stats/`. Non-authorized `indexes` are ommited from the response on `/stats`. Also add access to `GET` `indexes/:authorizedIndexes/stats`. |
| dumps | Provides access to `POST` `/dumps` and `GET` `/dumps/:dumpUid` routes. |

---

#### `POST` - `PUT` `/keys` payload

| field   | type    | required |description                     |
|---------|---------|----------|--------------------------------|
| actions | array | Required | A list of actions permitted for the API key. `["*"]` for all actions. **See Actions list definition part**. `*` character can be used as a wildcard. E.g. `documents.*` to authorize access on all documents endpoints. **Default**: `No default` |
| expiresInSeconds | integer | Optional | A number of seconds until the API Key will be valid. `null` or ommitted field equals to having no expiration time. **Default**: `null` |
| indexes  | array  |  Optional | `[*]` for all indexes. `*` character can be used as a wildcard. E.g. `products_*` to authorize access on all indexes starting with `products_`. **Default**: `["*"]` - All indexes |
| description | string  | Optional | A description for the API key. **Default**: `null` |

#### Request example

`POST` - `/keys`

##### Headers
```
"X-MEILI-API-KEY: :masterKey"
"Content-Type: application/json"
```
##### Body Payload
```json=
{
    "description": "Indexing API key",
    "indexes": ["products"],
    "actions": [
        "documents.add"
    ],
    "expiresInSeconds": 3600
}
```

##### Response

`200 Success`

```json=
{
    "key": "d0552b41536279a0ad88bd595327b96f01176a60c2243e906c52ac02375f9bc4",
    "createdAt": "2021-11-12T10:00:00.000000Z"
}
```

##### Possible Errors

- `actions` is mandatory and should be an array of `actions`
- If set, `description` shoud be a string
- If set, `indexes` should be an array of string
- If set, `expiresInSeconds` must be a positive integer

---

### **As `Anna`, I want to get details about an API key**

### `key` object representation

| field   | type    | description                                      |
|---------|---------|--------------------------------------------------|
| key     | string  | The generated key. **Generated by MeiliSearch**. |
| actions | array   | A list of actions permitted for the key. `["*"]` for all actions. See Actions list definition part. |
| indexes  | array  | A list of indexes permitted for the key. `["*"]` for all indexes. The `*` character can be used as a wildcard. E.g. `"products_*"` to authorize access on all indexes starting with `products_`. | 
| expiresInSeconds | integer | A number of seconds until the API Key will expires. `null` equals to no expiration. |
| description | string  | A description for the key. `null` if empty. |
| createdAt | string | Represent the date and time as `ISO-8601` format when the API key has been created. **Generated by MeiliSearch** |
| updatedAt | string | Represent the date and time as `ISO-8601` format when the API key has been updated. **Generated by MeiliSearch** |

#### Request example

`GET` - `/keys/d0552b41536279a0ad88bd595327b96f01176a60c2243e906c52ac02375f9bc4`

#### Headers

```
"X-MEILI-API-KEY: :masterKey"
```

#### Response

`200 Success`

```json=
{
    "description": "Indexing API key",
    "key": "d0552b41536279a0ad88bd595327b96f01176a60c2243e906c52ac02375f9bc4",
    "actions": [
        "documents.add"
    ],
    "indexes": [
        "products"
    ],
    "expiresInSeconds": 3550, //50 elapsed seconds since the API key creation request.
    "createdAt": "2021-11-12T10:00:00.000000Z",
    "updatedAt": "2021-11-12T10:00:00.000000Z"
}
```

#### Possible Errors
- `404 API Key Not Found`

### **As `Anna`, I want to lists the API Keys**

#### Request example

`GET` - `/keys/d0552b41536279a0ad88bd595327b96f01176a60c2243e906c52ac02375f9bc4`

#### Headers

```
"X-MEILI-API-KEY: :masterKey"
```

#### Response

`200 Success`

```json=
{
    "results": [
        {
            "description": "Indexing API key",
            "key": "d0552b41536279a0ad88bd595327b96f01176a60c2243e906c52ac02375f9bc4",
            "actions": [
                "documents.add"
            ],
            "indexes": [
                "products"
            ],
            "expiresInSeconds": 3550,
            "createdAt": "2021-08-13T10:00:00.000000Z",
            "updatedAt": "2021-08-13T10:00:00.000000Z"
        },
        {
            "description": "Default Search API Key (Use it to search from the frontend code)",
            "key": "0a6e572506c52ab0bd6195921575d23092b7f0c284ab4ac86d12346c33057f99",
            "actions": [
                "search"
            ],
            "indexes": [
                "*"
            ],
            "expiresInSeconds": null,
            "createdAt": "2021-08-11T10:00:00.000000Z",
            "updatedAt": "2021-08-11T10:00:00.000000Z"
        },
        {
            "description": "Default Admin API Key (Do not expose it on frontend side)",
            "key": "380689dd379232519a54d15935750cc7625620a2ea2fc06907cb40ba5b421b6f",
            "actions": [
                "*"
            ],
            "indexes": [
                "*"
            ],
            "expiresInSeconds": null,
            "createdAt": "2021-08-11T10:00:00.000000Z",
            "updatedAt": "2021-08-11T10:00:00.000000Z"
        }
    ],
}
```
> Expired `API keys` cannot be found on the `/keys` endpoints. They are deleted.
> 👉 Note the two default generated API keys. When a `master` key is set at MeiliSearch first-launch, we can generate two pre-configured Stored `API Keys`. A `Default Search API Key` restricted to the `search` action and a `Default Admin API Key` key to handle all operations (except managing API Keys) on MeiliSearch.

#### List details

- Keys are ordered by `createdAt` in desc order. (Most recent first)
- No pagination

---

### **As `Anna`, I want to update an API keys to change it's restrictions**

#### Request example

`PUT` - `/keys/d0552b41536279a0ad88bd595327b96f01176a60c2243e906c52ac02375f9bc4`

#### Headers
```
"X-MEILI-API-KEY: :masterKey"
"Content-Type: application/json"
```

#### Body Payload
```json=
{
    "description": "Manage Document API key",
    "indexes": ["products_*"], //Has now access to all indexes starting with `products_`
    "actions": [
        "documents.*" //Has now access to all operations on the documents API endpoint
    ],
    "expiresAt": null //Becomes unlimited
}
```

> ⚠️ Any ommited fields is restored to his default value. See "`POST` - `PUT` `/keys` payload" Part.

`200 Success`

```json=
{
    "key": "d0552b41536279a0ad88bd595327b96f01176a60c2243e906c52ac02375f9bc4",
    "updatedAt": "2021-08-14T10:00:00.000000Z"
}
```

#### Possible Errors
- `404 API Key Not Found`.
- `actions` is mandatory and must be an array of `actions`.
- If set, `description` must be a string.
- If set, `indexes` must be an array of string.
- If set, `expiresInSeconds` must.

---

### **As `Anna`, I want to delete an API key**

#### Request example

`DELETE` - `/keys/d0552b41536279a0ad88bd595327b96f01176a60c2243e906c52ac02375f9bc4`

#### Headers

```
"X-MEILI-API-KEY: :masterKey"
```

#### Response

`204 No-Content`

#### Possible Errors
- `404 API Key Not Found`.

---

### **As `Mark`, I am using an expired/deleted API Key**

#### Request example

`POST` - `/indexes/movies/search`

#### Headers

```
    "X-MEILI-API-KEY": "d0552b41536279a0ad88bd595327b96f01176a60c2243e906c52ac02375f9bc4"
```

#### Response

`403 Forbidden`
```json=
{
    "message": "The API Key provided is invalid.",
    "code": "invalid_api_key",
    "type": "auth_error",
    "link": "https://docs.meilisearch.com/errors#invalid_api_key"
}
```

---

### **As `Mark`, I am using a valid API Key but permission are not sufficient to access the resource**

#### Request example

`POST` - `/indexes/movies/search`

#### Headers

#### Response

`403 Forbidden`
```json=
{
    "message": "The API Key provided does not have sufficient permissions to access the requested resource.",
    "code": "insufficient_permissions",
    "type": "auth_error",
    "link": "https://docs.meilisearch.com/errors#insufficient_permission"
}
```

---

## Future Possibilities

- Add a generated `id` field to paginate the list of `API Key`? Thus, we don't expect much API keys to be created.
- Hard limit on number of API keys to be stored?
- Have an "archive" state where manually deleted API Keys can be restored.

**Comment by gmourier** [comment]
# Multi-Tenancy `Scoped API Key`

## Summary Key Points

- `Scoped API keys` are generated from a MeiliSearch `API key` on the client's server code to resolve multi-tenancy use-case by restricting access to data within an index according to the criteria chosen by the team managing a MeiliSearch instance. 
- These `Scoped API keys` can't be less restrictive than a parent `API key` and can only be used for search. 
- These `Scoped API keys` are not stored and thus retrievable on MeiliSearch. **This is why we highly advise setting an expiration time on that type of API key for security reasons.**

## Diagrams

### Solving Multi-Tenancy with `Scoped API Keys`

![](https://i.imgur.com/J4jVe1n.png)

Now imagine that Mark is a developer for a SaaS platform. He would like to ensure that an end-user can only access his documents at search time. **His database contains many users and he hopes to have many more in the future.**

When a user registers, the backend-side client code generates a `Scoped API Key` specifically for that end-user so that he can only access his documents. 

A `filter` parameter is set to restrict the search to document having a field `user_id` having the by the `user_id` as a value. This `filter` parameter is contained in the `Scoped API key's` payload and cannot be modified during the search by the end-user making the request. 

This `Scoped API Key` is generated from a parent `API key` that Anna provided before to authorize this `Scoped API Key` during search requests.

---

## Generating a `Scoped API Key`

We are still evaluating a solution to generate the Scoped API Key on the server-side client.

### Algolia / TypeSense way

```javascript
export const generateScopedApiKey = () => {
  return (apiKey: string, restrictions: scopedApiKeyRestrictions): string => {
    const queryParameters = serializeQueryParameters(restrictions);

    const securedKey = crypto
      .createHmac('sha256', apiKey)
      .update(queryParameters)
      .digest('hex');

    return Buffer.from(securedKey + queryParameters).toString('base64');
  };
};
```

### JWT

```js=
header = { 
  "alg": "HS256", 
  "typ": "JWT" 
}
payload = {
  filter: "user_id = 1",
  expiresIn: 3600
}
signature = HMACSHA256(
   base64UrlEncode(header) + "." +
   base64UrlEncode(payload),
   apiKey //secret
)

scopedApiKey = base64UrlEncode(header) + "." + base64UrlEncode(payload) + "." + signature
=> "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMjNhYmMiLCJmaXJzdF9uYW1lIjoiSmVhbiIsImxhc3RfbmFtZSI6IkR1cG9udCIsImVtYWlsIjoiamVhbmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTUxNjIzOTAyMn0.ITnJo8VwbP4PkVTANSt651C0olsrdRNCNmvTHkanuYk"
```

### Biscuit

https://github.com/CleverCloud/biscuit-rust

**Comment by gmourier** [comment]
Specified https://github.com/meilisearch/specifications/pull/85

**Comment by raphaeltm** [comment]
A question regarding arrays.

Let's say you have an index for "Tasks" with data like:

```
{
  "id": 1,
  "title": "task title",
  "collaborators": ["user1", "user2"],
}
{
  "id": 2,
  "title": "other title",
  "collaborators": ["user1", "user3"],
}
{
  "id": 3,
  "title": "last title",
  "collaborators": ["user2", "user3"],
}
```

We create a Scoped API Key:

```
{
     "indexesPolicy": {
         "tasks": {
             "filter": "collaborators = 'user1'"
         }
     },
    "expiresIn": 3600
}
```

In my ideal world, creating this Scoped API Key essentially creates a subset of `tasks` to run any filters against.

So if I use that Scoped API Key when `user1` is logged in, they should still be able to pass a query like:

```
{ 
  "q": "title", 
  "filter": "collaborators = 'user2'" 
}
```

And they should only get back the task with the id 1. Essentially my assumption is that all filters in the Scoped API Keys would be `AND`ed with whatever filters a user might pass through.

Is that what's being proposed with this?

**Comment by gmourier** [comment]
Hello @raphaeltm 👋

Thanks for this example. Indeed, this is the expected behavior of filters. User1 will not be able to just remove his built-in filter in his Scoped API Keys.

You might also want to hide this field in the search results by leaving it out of the `displayedAttributes` settings so that User1 does not know who else has access to the document.

**Comment by raphaeltm** [comment]
Hey @gmourier. Awesome. I just wanted to clarify, because this threw me off a bit:

> Note that filters defined for a Scoped API Key cannot be overwritten at search and will be discarded.

But your clarification makes sense to me 🙂  They can't overwrite it, but they can _refine_ it.

**Comment by gmourier** [comment]
Thanks, @raphaeltm. I've rephrased it!

**Comment by gmourier** [comment]
✨ v0.26.0 version adds multi-tenancy support to the search with the tenant tokens feature.
