### ISSUE TITLE
`q` search parameter : Add negative operator `-`

### ISSUE THREAD

**Issue by gmourier** [meilisearch/product#53]
# Description

Add an operator to eliminate the presence of a term from the documents to be retrieved as search results.

As an end-user, I want to eliminate documents containing the term chatbot while I'm searching to get a refund.

e.g. `"q": "-chatbot How to get a refund?"`

**Comment by gmourier** [comment]
This topic has not moved in the past 6 months, so it is closed. The issue can be re-opened if the need arises.

**Comment by AlejandroAkbal** [comment]
I'm still interested in this feature, please let me know when/if it's implemented

**Comment by gmourier** [comment]
Hi @AlejandroAkbal 👋

I invite you to come [here](https://github.com/meilisearch/product/discussions/181) to discuss this need.

Thanks!
