### ISSUE TITLE
`MEILI_MAX_INDEX_SIZE` / `--max-index-size` explanations are missleading.

### ISSUE THREAD

**Issue by gmourier** [meilisearch/product#530]
## Description

The documentation explains:

Sets the maximum size of the index. Value must be given in bytes or explicitly stating a base unit. For example, the default value can be written as 107374182400, '107.7Gb', or '107374 Mb'.

The index stores processed data and is different from the task database, which handles [pending tasks](https://docs.meilisearch.com/learn/advanced/asynchronous_operations.html).

The CLI helper explains:

```
       --max-index-size <MAX_INDEX_SIZE>
            The maximum size, in bytes, of the main lmdb database directory

            [env: MEILI_MAX_INDEX_SIZE=]
            [default: "100 GiB"]
```

The name of the configuration helper explanation leads me to believe that it is a size for all index, which is wrong. In reality, this is a size per index.

## Ideas

- Display clearer information in the documentation. e.g Instead of saying `Sets the maximum size of the index`, we could say `Sets the maximum size of an index`. 
- Rephrase the CLI helper.

**Comment by curquiza** [comment]
> The name of the configuration and the documentation explanation lead me to believe that it is a size by index, which is wrong. It is the size of the LMDB database which stores all the indexes.

I did not know, I thought it was the size of one index....

**Comment by gmourier** [comment]
I've updated the issue @curquiza. The problem is just that the CLI helper is not clear because this is a size per index!

**Comment by gmourier** [comment]
Closed since [specified](https://github.com/meilisearch/specifications/pull/187) and planned for `v0.30` release.
