### ISSUE TITLE
Index in RocksDB then compact to LMDB

### ISSUE THREAD

**Issue by gmourier** [meilisearch/product#68]
# Description

RocksDB is an LSM Tree (High throughput on writes)
LMDB is a B+ Tree (High throughput on reads)

it could be possible to create a kind of KVStore that will use RocksDB for writes and both for reads. All indexations will be put into the RocksDB and after a while when RocskDB is too big, the compaction creates a final data that will be merged to the LMDB.

**Comment by Hadryan** [comment]
Please take a look at https://github.com/KvrocksLabs/kvrocks

**Comment by gmourier** [comment]
This topic has not moved after 6 months, so it is closed. The issue can be re-opened if the need arises.
