### ISSUE TITLE
Add ellipsis text on cropped search results

### ISSUE THREAD

**Issue by gmourier** [meilisearch/product#70]
# Description

Some users ask to be able to have directly the information where the text is cropped. The only way today is to use `matches` query parameter and parse `_matchesInfo` result to add this information on the client-side of the search results. It requires adding code on the front side which does not make life easier for the user.

Adding an ellipsis by default like `...` in front or behind the cropped text might be enough to fulfill this user's need. We could also consider adding an option to specify user's own string.

**Comment by interlark** [comment]
Cool! I found this feature pretty useful. You can see you use it yourself in your search widget. It puts ellipsis sometimes in wrong places.

The reason why you put ellipsis wrong sometimes is that you're trying to guess whether you should put them behind or after a fragment looking at leading letter's case and trailing character - you put ellipsis anywhere after, except special characters like [?!]. And anywhere behind where you find lowercased character.

https://github.com/meilisearch/docs-searchbar.js/blob/828914558ec287295d989189c9931b9fb115fb5e/src/lib/utils.js#L284

![image](https://user-images.githubusercontent.com/20641837/126612283-a96d252c-f32a-48ff-b89c-04c28c922693.png)

**Comment by gmourier** [comment]
Thanks for the feedback! Indeed the `...` markers are placed at the beginning and end of the cropped strings that are returned by the engine. It is the client that does the work of adding them.

The goal of this feature would be to automate this action from the engine and return the cropped text with the right position for the ellipsis marker!

**Comment by gmourier** [comment]
Closed since [specified](https://github.com/meilisearch/specifications/pull/120) and planned for **v0.27** release.
